name: Build Release (Docker)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g., v1.0.0)'
        required: false
        default: 'test'

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up tag name
      id: tag
      run: |
        if [ -n "${{ github.event.inputs.tag }}" ]; then
          echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
        else
          echo "tag=dev-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
        fi
    
    # Build custom Docker image and run build
    - name: Build game with Docker
      run: |
        # Build the custom Docker image
        docker build -t commander-keen-builder .
        
        # Run the build using our custom image and build script
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          commander-keen-builder
    
    - name: List built artifacts
      run: |
        echo "Built artifacts:"
        ls -la artifact/
    
    - name: Create release zip files
      run: |
        cd artifact
        
        # Package Windows build
        if [ -f commander-keen-windows.exe ]; then
          zip -r commander-keen-windows-${{ steps.tag.outputs.tag }}.zip commander-keen-windows.exe
        fi
        
        # Package Linux build
        if [ -f commander-keen-linux.x86_64 ]; then
          chmod +x commander-keen-linux.x86_64
          zip -r commander-keen-linux-${{ steps.tag.outputs.tag }}.zip commander-keen-linux.x86_64
        fi
        
        # Rename macOS build if it exists
        if [ -f commander-keen-macos.zip ]; then
          mv commander-keen-macos.zip commander-keen-macos-${{ steps.tag.outputs.tag }}.zip
        fi
        
        echo "Final release files:"
        ls -la *.zip
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: commander-keen-builds-${{ steps.tag.outputs.tag }}
        path: artifact/*.zip