name: Build Release

on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g., v1.0.0)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5 
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up tag name
      id: tag
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.tag }}" ]; then
          echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
        elif [ "${{ github.event_name }}" = "push" ]; then
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        elif [ "${{ github.event_name }}" = "release" ]; then
          echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
        else
          echo "tag=dev-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
        fi
    
    # Build custom Docker image and run build
    - name: Build game with Docker
      run: |
        # Build the custom Docker image
        docker build -t commander-keen-builder .
        
        # Run the build using our custom image and build script
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          commander-keen-builder
    
    - name: List built artifacts
      run: |
        echo "Built artifacts:"
        ls -la artifact/
    
    - name: Create release zip files
      run: |
        cd artifact
        
        # Verify that all expected files were built
        missing_files=0
        
        if [ ! -f commander-keen-windows.exe ]; then
          echo "ERROR: Windows build file missing!"
          missing_files=$((missing_files + 1))
        fi
        
        if [ ! -f commander-keen-linux.x86_64 ]; then
          echo "ERROR: Linux build file missing!"
          missing_files=$((missing_files + 1))
        fi
        
        if [ ! -f commander-keen-macos.zip ]; then
          echo "ERROR: macOS build file missing!"
          missing_files=$((missing_files + 1))
        fi
        
        if [ $missing_files -gt 0 ]; then
          echo "ERROR: $missing_files build files are missing. Aborting release packaging."
          exit 1
        fi
        
        # Package Windows build
        zip -r commander-keen-windows-${{ steps.tag.outputs.tag }}.zip commander-keen-windows.exe
        
        # Package Linux build
        chmod +x commander-keen-linux.x86_64
        zip -r commander-keen-linux-${{ steps.tag.outputs.tag }}.zip commander-keen-linux.x86_64
        
        # Rename macOS build
        mv commander-keen-macos.zip commander-keen-macos-${{ steps.tag.outputs.tag }}.zip
        
        echo "Final release files:"
        ls -la *.zip
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: commander-keen-windows-${{ steps.tag.outputs.tag }}
        path: artifact/commander-keen-windows-${{ steps.tag.outputs.tag }}.zip

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: commander-keen-linux-${{ steps.tag.outputs.tag }}
        path: artifact/commander-keen-linux-${{ steps.tag.outputs.tag }}.zip

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: commander-keen-macos-${{ steps.tag.outputs.tag }}
        path: artifact/commander-keen-macos-${{ steps.tag.outputs.tag }}.zip

    - name: Upload to release
      if: github.event_name == 'release' || github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        files: |
          artifact/commander-keen-windows-${{ steps.tag.outputs.tag }}.zip
          artifact/commander-keen-linux-${{ steps.tag.outputs.tag }}.zip
          artifact/commander-keen-macos-${{ steps.tag.outputs.tag }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}