name: .NET format

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '.github/workflows/format-code.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '.github/workflows/format-code.yml'

jobs:
  dotnet-format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
    - name: Restore dependencies
      run: dotnet restore
    - name: Format
      run: dotnet format Commander-keen.sln --verify-no-changes --verbosity diagnostic
